### GET ALL POSTS
GET http://localhost:3000/post

#### GET POST BY ID
GET http://localhost:3000/post/22

### UPDATE POST
PATCH http://localhost:3000/post/1
Content-Type: application/json

{
  "title": "Updated Post Again",
  "content": "This is the updated content of the post."
}

### DELETE POST 
DELETE http://localhost:3000/post/22

### DELETE POST HARD DELETE
DELETE http://localhost:3000/post/12?hard=true

### CREATE USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@test1.net",
  "password": "123456"
}

### Update USER
PATCH http://localhost:3000/users/1 
Content-Type: application/json

{
  "name": "John Doe Silva",
  "password": "123456789"
}

### GET ALL USERS
GET http://localhost:3000/users

### GET USER BY ID
GET http://localhost:3000/users/1

### DELETE USER
DELETE http://localhost:3000/users/1

### DELETE USER HARD DELETE
DELETE http://localhost:3000/users/50?hard=true